---
title: Biostats 597F
subtitle: Week 4 - R Review
output: ioslides_presentation
---

## Data frame

- Data frame is most used object for data analysis and modeling
- It looks like matrix, but these 2 are fundamentally different
```
class(mtcars)
mode(mtcars)
attributes(mtcars)
```
    - Matrix is a vetor, while data frame is a list
    - All elements in matrix must have same mode, while data frame only need to have same mode for each column
- A data frame is a special list with each component with same length
- Similar to SQL data and SAS data

## Create data frame

- **data.frame()** function
```
data.frame(x = 1:10, 
           y = letters[1:10])
```

- Read from external file (csv, txt, excel, etc)

- When creating data frame, we should almost alway set **stringsAsfactors = FALSE**. Factor variables often gives trouble.
```
data.frame(x = 1:10, 
           y = letters[1:10], stringsAsFactors = FALSE)
```

## Access data frame

We can use list operators to access data frame columns

```
mtcars[["cyl"]]
mtcars$cyl
mtcars[1:3]
mtcars[c("mpg", "disp")]
```

## Matrix like operators

We can extract elements by row and column as for matrix

```
mtcars[1:5, 1:4]
mtcars[1:5, c("hp", "cyl")]
mtcars[mtcars$cyl == 6, ]
```

## Common data frame operations

- mutate
- arrange
- select
- group wise operations/aggregations
- data merge

All those can be easily achieved by **dplyr** package. This worths a couple of lecturs to discuss.

## Factors

- Factor is a vector
- Factor is a numeric vector with additional attributes: **levels** and **class**
- Using factor may produce confusing results, so use with caution!! Use factors when you know what you are doing
- Essentially factor has levels to be unique values, while the value stored is index of levels
```
x <- c("A", "B", "A", "C")
x <- factor(x)
class(x)
typeof(x)
mode(x)
attributes(x)
```

## Factor to numeric

If we convert factor to numeric, it will be the integer values it stored, not the original values if levels are numeric

```
x <- factor(c(5, 6, 5, 8))
y <- factor(c("A", "B", "B"))
as.numeric(x)
as.numeric(y)
```

We should almost always set **stringsAsFactor = FALSE** while we read a csv data to avoid potential errornous numeric conversion.

## Working with levels

- Levels of a factor is created once the factor is created. Very tricky while with with new values

```
x <- factor(c(5, 6, 3, 4))
x[1] <- 12   # Result not anticipated
c(x, 12) # converted to numeric (1, 2, 3...)
c(x, "A")
```

- We modify levels or specify level while creating factor

```
x <- factor(c(5, 6, 3, 4))
levels(x) <- c(3, 5, 8, 2)  # anything wrong?
levels(x) <- c(levels(x), 18)
x[1] <- 18
factor(c(5, 4, 3, 3, 4), levels = c(5, 3, 4)) #default levels are by order
```

## Working with levels

- What happens combining two factors?
```
x <- factor(c(3, 4))
y <- factor(c(4, 5))
c(x, y)
```

- relevel in modeling (specify reference level for categorical variable)

```
mtcars$cyl <- factor(mtcars$cyl)
fit <- lm(mpg ~ disp + cyl, data = mtcars)
summary(fit)
mtcars$cyl <- relevel(mtcars$cyl, ref = "8")
fit <- lm(mpg ~ disp + cyl, data = mtcars)
summary(fit)
```

## cut() function

- cut() function is used to discretize numeric variable, which is very useful in predictive modeling

Example: convert numeric vector x into quartiles

```
x <- rnorm(1000)
q4 <- quantile(x, c(0.25, 0.5, 0.75))
cut(x, breaks = c(-Inf, q4, Inf))
cut(x, breaks = c(-Inf, q4, Inf), 
       labels = c("Q1", "Q2", "Q3", "Q4"))
```

There are handy functions in ggplot2
```
library(ggplot2)
cut_number(x, 4)  # equal number
cut_interval(x, 4) # equal distance
```

## Apply functions family

Apply functions can replace your loops and make your code concise

Commonly used apply functions

- **apply**: Apply Functions Over Array Margins
- **sapply** and **lapply**: Apply a Function over a List or Vector
- **tapply**: Apply a Function Over a Ragged Array

Less commonly used apply functions:

- **by**: Apply a Function to a Data Frame Split by Factors
- **eapply**: Apply a Function Over Values in an Environment
- **mapply**: Apply a Function to Multiple List or Vector Arguments
- **rapply**: Recursively Apply a Function to a List

## apply function

```
apply(X, MARGIN, FUN, ...)
```

Returns a vector or array or list of values obtained by applying a function to margins of an array or matrix. MARGIN 1 is by row, 2 is by column

```
m <- matrix(1:12, nrow = 3)
apply(m, 1, sum)
apply(m, 2, max)  # max of each column
```

Function may return vector length longer than 1, or even anything

```
m <- matrix(1:10, nrow = 5)
apply(m, 1, function(x) x[x > 3])
```

## sapply and lapply functions

lapply returns a list of the same length as X, each element of which is the result of applying FUN to the corresponding element of X. 

sapply is a user-friendly version and wrapper of lapply by default returning a vector, matrix

for example:

- If returned list containing elements with length 1, then sapply will simplify to single list
```
lapply(1:5, function(x) x)
sapply(1:5, function(x) x)
```

## sapply and lapply functions

- If returned list containing vectors with same length, sapply will simplify to matrix
```
lapply(1:5, function(x) rep(x, 5))
sapply(1:5, function(x) rep(x, 5))
```

data frame is a list, so lapply/sapply can be used to apply functions to each column

```
sapply(mtcars, class)
sapply(mtcars, is.character)

# mean for numeric variables
sapply(mtcars[, sapply(mtcars, is.numeric)], mean)
```

## sapply and lapply functions

Can also be used to simulation, which equivalent to for loop

Example: power of t-test, assume delta = 0.1, N = 100

```
test <- function(x) t.test(rnorm(100, 0.1))$p.value < 0.05
reject <- sapply(1:10000, test)
mean(reject)
```

## do.call() to collect a list of results

We often want to combine a list of results returned from lapply

Example: combine a list of data frame

```
files <- c("mtcars1.csv", "mtcars2.csv", "mtcars3.csv")
data <- lapply(files, function(x) read.csv(x, stringsAsFactors = F))
data_combined <- do.call("rbind", data)
```

## tapply function

Apply a function to each cell of a ragged array, that is to each (non-empty) group of values given by a unique combination of the levels of certain factors.

```
tapply(X, INDEX, FUN, ..., simplify = TRUE)
```

```
ages <- c(25,26,55,37,21,42)
affils <- c("R","D","D","R","U","D")
tapply(ages,affils,mean)
```

Excersise -

in mtcars data, find the average mpg for each number of cyl
